version : '3'
services:
  service-back:
    image: tombenpotter/microservices-tp2:0.1
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=dev
    networks:
      - backend
    expose:
      - "8080"
#    volumes:
#      - "./logs:/logs"

  service-front:
    image: tombenpotter/microservices-tp2-front:0.1
    ports:
      - "1010:1010"
    environment:
      - APP_PORT=1010
      - WS_BACK_URL=172.17.0.1
    networks:
      - backend

networks:
  backend:
    driver: bridge
